### PR TITLE
Implement idna_encode/decode for zone and record names

### PR DESCRIPTION
**Pull request by ross**
This adds IDNA support to fqdns (zone and record names.) It also has fairly through tests of the functionality which helped me track down a couple bugs. It does not add support to record values. That will likely come in a later PR. It also (probably) doesn't support dynamic records. That too will be implemented and tested in a later PR.

/cc https://github.com/octodns/octodns-ns1/pull/20 which was an earlier pass at IDNA support
/cc https://github.com/octodns/octodns/issues/199 for central IDNA functionality tracking

### CODE REVIEW

**Review by viranch — APPROVED** [review]
LGTM! Should we explicitly check for IDN in dynamic record label and throw a warning/exception?

**Comment by ross** [comment]
> LGTM! Should we explicitly check for IDN in dynamic record label and throw a warning/exception?

As of right now things throw an invalid FQDN from octoDNS core:

Basic record:

```
octodns.record.ValidationError: Invalid record cname.zajęzyk.pl.
  - CNAME value "zajęzyk2.bar.com." is not a valid FQDN
```

Dynamic record:

```
octodns.record.ValidationError: Invalid record cname.zajęzyk.pl.
  - CNAME value "zajęzyk1.bar.com." is not a valid FQDN
  - CNAME value "zajęzyk2.bar.com." is not a valid FQDN
```

which seems like reasonable behavior. 

Once https://github.com/octodns/octodns/pull/915 ships that would change, but I've held off on that on purpose as I want to think through the details/staging of rolling that out.

**Comment by ross** [comment]
You got me thinking about this a bit more and I'm actually leaning towards adding yet another SUPPORTS flag and validation for IDNA. Seems like since some providers will support it and others won't that it'll be best to flag that out clearly at plan time (and not just blow up during apply.)  It may also makes sense to do a multi-level flag (zones & names, values, and dynamic.) 

Going to hold on shipping this until that's all thought/mapped out in detail. Good news is that what's in octoDNS core (and released) won't impact anything and will just sit there unused. 

Probably should have mapped out a plan beforehand, but it's not like I'm getting paid to think about all this anymore so I'm a little faster and looser than in the past :grin:

**Comment by ross** [comment]
Deeper I dig the messier this gets. I'm realizing now that if a provider supports IDNA and a user has configured a manually translated zone (as is required prior to octoDNS IDNA support) then the changes like this will break their setup as they'll have `xn--...` zones and records in the config and when the provider pulls that data down during `populate` it'll be translating it to the utf-8 equivilent and the two zones being compared won't even match.

I'm abandoning this and all of the existing idna PRs for the moment as I feel like the path things are going down will not be viable. Good news is the `ida_encode/decode` shipped in octoDNS still makes sense and nothing else has actually be part of a merged PR/release so we should be in an ok state until things are figured out.

**Pull request closed without merging**
