### PR TITLE
IDNA support

### PR DESCRIPTION
**Pull request by ross**
/cc https://github.com/octodns/octodns/issues/199
/cc https://github.com/octodns/octodns/pull/903

### CODE REVIEW

**Comment by viranch** [comment]
Does this also handle IDN support in FQDN-type answers like CNAME and MX? Even TXT records? Or does octoDNS core take care of that?

**Comment by ross** [comment]
> Does this also handle IDN support in FQDN-type answers like CNAME and MX? Even TXT records? Or does octoDNS 
core take care of that?

Heh. Nice catch. Was just going through the process of testing things and ran into the fact that it doesn't, and there are currently validation issues with utf-8 chars in record values.

Do IDN MX/SRV/NS records make sense? Even with CNAMEs the value people will see will be the encoded version since the DNS system itself doesn't know anything about the original utf-8 values and software likely wouldn't support running values in responses through their own decode/encode. octoDNS can definitely support it, I even have a not yet committed set of changes to octoDNS core to fix the validation issues.

It should be easy enough to encode/decode values here in NS so it probably makes sense to do it, my questions above are more thinking out loud about how the IDNA solution is kind of hacky in that it would let you think in utf-8, but when clients go to use it for anything "down the line" in values etc they'd be using/seeing the `xn-...` versions.

**Comment by ross** [comment]
hrm, getting internal sever errors when I try and create dynamic CNAMEs with IDNA, specifically in the monitor create call:

```python
{'active': True,
 'config': {'connect_timeout': 2000,
            'host': 'xn--zajzyk1-c9a.bar.com',
            'port': 443,
            'response_timeout': 10000,
            'send': 'GET /_dns HTTP/1.0\\r\\nHost: '
                    'cname.zajęzyk.pl\\r\\nUser-agent: NS1\\r\\n\\r\\n',
            'ssl': True},
 'frequency': 60,
 'job_type': 'tcp',
 'name': 'cname.zajęzyk.pl - CNAME - xn--zajzyk1-c9a.bar.com',
 'notes': 'host:cname.zajęzyk.pl type:CNAME',
 'notify_list': '62f29339f6491b0095148771',
 'policy': 'quorum',
 'rapid_recheck': False,
 'region_scope': 'fixed',
 'regions': ['lga'],
 'rules': [{'comparison': 'contains', 'key': 'output', 'value': '200 OK'}]}
```

I'm not 100% sure whether the Host header should use the utf-8 or idna version of the name (utf-8 makes more sense to me) but otherwise I don't see anything in here that should trip NS1 up. Maybe it doesn't like the `--` in the host?  I'm going to poke around a little bit more, but if I don't figure out what's up quickly I make break this PR up into 2. The first adding IDNA support for "simple" records and then leaving dynamic record support for a later (more complicated) PR.

**Comment by viranch** [comment]
Or keep this even simpler with IDN support only for zone names and record labels. Leave value support for future when a use case actually arises 🤷‍♂️

**Comment by ross** [comment]
Closing this in favor of https://github.com/octodns/octodns-ns1/pull/22

**Pull request closed without merging**
